version: '3'
services:
    mailhook:
        container_name: "mailhook"
        image: "nyanim/mailhook:latest"
        ports:
         - "5000:5000"
        volumes:
         - "./config.json:/usr/src/app/config.json"
        restart: always